name: dl
channels:
- defaults
dependencies:
- bleach=2.1.2
- ca-certificates=2017.08.26
- certifi=2018.1.18
- dbus=1.12.2
- decorator=4.2.1
- entrypoints=0.2.3
- expat=2.2.5
- fontconfig=2.12.4
- freetype=2.8
- glib=2.53.6
- gmp=6.1.2
- gst-plugins-base=1.12.4
- gstreamer=1.12.4
- html5lib=1.0.1
- icu=58.2
- intel-openmp=2018.0.0
- ipykernel=4.8.0
- ipython=6.2.1
- ipython_genutils=0.2.0
- ipywidgets=7.1.0
- jedi=0.11.1
- jinja2=2.10
- jpeg=9b
- jsonschema=2.6.0
- jupyter=1.0.0
- jupyter_client=5.2.2
- jupyter_console=5.2.0
- jupyter_core=4.4.0
- libedit=3.1
- libffi=3.2.1
- libgcc-ng=7.2.0
- libgfortran-ng=7.2.0
- libpng=1.6.34
- libsodium=1.0.15
- libstdcxx-ng=7.2.0
- libxcb=1.12
- libxml2=2.9.7
- markupsafe=1.0
- mistune=0.8.3
- mkl=2018.0.1
- nbconvert=5.3.1
- nbformat=4.4.0
- ncurses=6.0
- notebook=5.3.1
- numpy=1.14.0
- openssl=1.0.2n
- pandas=0.22.0
- pandoc=1.19.2.1
- pandocfilters=1.4.2
- parso=0.1.1
- pcre=8.41
- pexpect=4.3.1
- pickleshare=0.7.4
- pip=9.0.1
- prompt_toolkit=1.0.15
- ptyprocess=0.5.2
- pygments=2.2.0
- pyqt=5.6.0
- python=3.6.4
- python-dateutil=2.6.1
- pytz=2017.3
- pyzmq=16.0.3
- qt=5.6.2
- qtconsole=4.3.1
- readline=7.0
- send2trash=1.4.2
- setuptools=38.4.0
- simplegeneric=0.8.1
- sip=4.18.1
- six=1.11.0
- sqlite=3.21.0
- terminado=0.8.1
- testpath=0.3.1
- tk=8.6.7
- tornado=4.5.3
- traitlets=4.3.2
- wcwidth=0.1.7
- webencodings=0.5.1
- wheel=0.30.0
- widgetsnbextension=3.1.0
- xz=5.2.3
- zeromq=4.2.2
- zlib=1.2.11
- pip:
  - absl-py==0.1.9
  - futures==3.1.1
  - ipython-genutils==0.2.0
  - jupyter-client==5.2.2
  - jupyter-console==5.2.0
  - jupyter-core==4.4.0
  - keras==2.1.3
  - markdown==2.6.11
  - prompt-toolkit==1.0.15
  - protobuf==3.5.1
  - pyyaml==3.12
  - scipy==1.0.0
  - tensorflow-gpu==1.5.0
  - tensorflow-tensorboard==1.5.0
  - werkzeug==0.14.1
prefix: /home/fabio/miniconda3/envs/dl

